#!/usr/bin/env python3
"""Update or check the generated shapr compatibility table in the README."""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

PYTHON_ROOT = Path(__file__).resolve().parents[1]
POLICY_PATH = PYTHON_ROOT / "src" / "pyshapr" / "compatibility.toml"
README_PATH = PYTHON_ROOT / "README.md"
BEGIN_MARKER = "<!-- BEGIN GENERATED SHAPR COMPATIBILITY -->"
END_MARKER = "<!-- END GENERATED SHAPR COMPATIBILITY -->"


def _format_features(features: list[str]) -> str:
    if len(features) == 1:
        return features[0]
    if len(features) == 2:
        return " and ".join(features)
    return f"{', '.join(features[:-1])}, and {features[-1]}"


def _render_table() -> str:
    with POLICY_PATH.open("rb") as policy_file:
        policy = tomllib.load(policy_file)

    if policy.get("schema_version") != 1:
        raise ValueError("Unsupported compatibility.toml schema version")

    shapr = policy["shapr"]
    minimum_supported = shapr["minimum_supported"]
    developed_with = shapr["developed_with"]
    full_support_boundary = shapr["recent_features_require_newer_than"]
    unavailable_features = _format_features(shapr["unavailable_features"])

    return "\n".join(
        [
            BEGIN_MARKER,
            "<!-- Generated by scripts/update_compatibility_table.py; do not edit manually. -->",
            "| Minimum `shapr` | Developed with | Full feature support | Limited support |",
            "|---|---|---|---|",
            (
                f"| `{minimum_supported}` | `{developed_with}` | "
                f"`shapr > {full_support_boundary}` | "
                f"`shapr <= {full_support_boundary}`: {unavailable_features} unavailable |"
            ),
            END_MARKER,
        ]
    )


def _updated_readme() -> str:
    readme = README_PATH.read_text(encoding="utf-8")
    before, begin_marker, remainder = readme.partition(BEGIN_MARKER)
    generated_block, end_marker, after = remainder.partition(END_MARKER)
    if not begin_marker or not end_marker:
        raise ValueError("README compatibility markers are missing")

    del generated_block
    return f"{before}{_render_table()}{after}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if README.md is out of date")
    args = parser.parse_args()

    current_readme = README_PATH.read_text(encoding="utf-8")
    updated_readme = _updated_readme()
    if args.check:
        if current_readme != updated_readme:
            print("README compatibility table is out of date.", file=sys.stderr)
            print("Run: python scripts/update_compatibility_table.py", file=sys.stderr)
            return 1
        return 0

    README_PATH.write_text(updated_readme, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
