# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get distance
#'
#' @param Xtrain Dataframe
#' @param Xtest Dataframe
#'
#' @export
#'
#' @return Array of three dimensions
#' @author Nikolai Sellereite
distance_cpp <- function(Xtrain, Xtest) {
    .Call(`_shapr_distance_cpp`, Xtrain, Xtest)
}

#' Get imputed data
#'
#' @param ID Positive integer vector
#' @param Comb Positive integer vector
#' @inheritParams global_arguments
#'
#'
#' @export
#'
#' @return Array of three dimensions
#' @author Nikolai Sellereite
impute_cpp <- function(ID, Comb, Xtrain, Xtest, S) {
    .Call(`_shapr_impute_cpp`, ID, Comb, Xtrain, Xtest, S)
}

#' Get distance
#'
#' @param n Postive integer. Number of combinations
#' @inheritParams global_arguments
#'
#' @export
#'
#' @return Matrix of dimension n x m + 1
#' @author Nikolai Sellereite
weighted_matrix <- function(features, m, n) {
    .Call(`_shapr_weighted_matrix`, features, m, n)
}

#' Get feature matrix
#'
#' @param features List
#' @param nfeatures Positive integer. Total number of features
#'
#' @export
#'
#' @return Matrix
#' @author Nikolai Sellereite
feature_matrix_cpp <- function(features, nfeatures) {
    .Call(`_shapr_feature_matrix_cpp`, features, nfeatures)
}

#' Get distance
#'
#' @inheritParams global_arguments
#'
#' @export
#'
#' @return Matrix of dimension n x m + 1
#' @author Nikolai Sellereite
weights_train_comb_cpp <- function(D, S, sigma) {
    .Call(`_shapr_weights_train_comb_cpp`, D, S, sigma)
}

