# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computing single H matrix in AICc-function using the Mahalanobis distance
#'
#' @param x_mat matrix with "covariates"
#' @param mcov covariance matrix
#' @param S_scale_dist logical indicating whether the Mahalanobis distance should be scaled with the number of variables
#' @param h numeric specifying the scaling (sigma)
#'
#' @export
#'
#' @return Matrix of dimension \code{ncol(x)*ncol(x)}
#' @author Martin Jullum
hat_matrix_cpp <- function(x_mat, mcov, S_scale_dist, h) {
    .Call(`_shapr_hat_matrix_cpp`, x_mat, mcov, S_scale_dist, h)
}

#' sigma_hat_sq-function
#'
#' @param H Matrix. Output from \code{\link{hat_matrix_cpp}}
#' @param y Vector, i.e. representing the response variable
#' @param ret_log Logical. Indicates whether to return the logarithm of \code{sigma_sq}
#' @export
#'
#' @return Scalar
#' @author Martin Jullum
rss_cpp <- function(H, y) {
    .Call(`_shapr_rss_cpp`, H, y)
}

#' correction term with trace_input in AICc formula
#'
#' @param tr_H numeric giving the trace of H
#' @param n numeric given the number of rows in H
#' @export
#'
#' @return Scalar
#' @author Martin Jullum
correction_matrix_cpp <- function(tr_H, n) {
    .Call(`_shapr_correction_matrix_cpp`, tr_H, n)
}

#'  Temp-function for computing the full AICc with several X's etc
#'
#' @param x matrix with "covariates"
#' @param mcov covariance matrix
#' @param S_scale_dist logical indicating whether the Mahalanobis distance should be scaled with the number of variables
#' @param h numeric specifying the scaling (sigma)
#' @param y vector with the "response variable"
#'
#' @export
#'
#' @return Scalar with the numeric value of the AICc formula
#' @author Martin Jullum
aicc_full_single_cpp <- function(x, mcov, S_scale_dist, h, y) {
    .Call(`_shapr_aicc_full_single_cpp`, x, mcov, S_scale_dist, h, y)
}

#'  AICc formula for several sets, alternative definition
#'
#' @param h numeric specifying the scaling (sigma)
#' @param x matrix with "covariates"
#' @param mcov covariance matrix
#' @param S_scale_dist logical indicating whether the Mahalanobis distance should be scaled with the number of variables
#' @param y vector with the "response variable"
#'
#' @export
#'
#' @return Scalar with the numeric value of the AICc formula
#' @author Martin Jullum
aicc_full_cpp <- function(h, x_list, mcov_list, S_scale_dist, y_list, negative) {
    .Call(`_shapr_aicc_full_cpp`, h, x_list, mcov_list, S_scale_dist, y_list, negative)
}

#' (Generalized) Mahalanobis distance
#'
#' Used to get the Euclidean distance as well by setting \code{mcov} = \code{diag(m)}.
#'
#' @param feature_list List of vectors indicating all factor combinations that should be included in the computations. Assumes that the first one is empty.
#' @param mcov Matrix. The Sigma-matrix in the Mahalanobis distance formula (\code{stats::cov(xtrain_mat)}) gives Mahalanobis distance,
#' \code{diag(m)} gives the Euclidean distance.
#' @param S_scale_dist Logical indicating
#'
#' @export
#'
#' @return Array of three dimensions. Contains the squared distance for between all training and test observations for all feature combinations passed to the function.
#' @author Martin Jullum
mahalanobis_distance_cpp <- function(feature_list, xtrain_mat, xtest_mat, mcov, S_scale_dist) {
    .Call(`_shapr_mahalanobis_distance_cpp`, feature_list, xtrain_mat, xtest_mat, mcov, S_scale_dist)
}

#' Get imputed data
#'
#' @param id Positive integer vector
#' @param Comb Positive integer vector
#' @inheritParams global_arguments
#'
#'
#' @export
#'
#' @return Array of three dimensions
#' @author Nikolai Sellereite
observation_impute_cpp <- function(id, Comb, xtrain, xtest, s) {
    .Call(`_shapr_observation_impute_cpp`, id, Comb, xtrain, xtest, s)
}

#' Get distance
#'
#' @param n Positive integer. Number of combinations
#' @inheritParams global_arguments
#'
#' @export
#'
#' @return Matrix of dimension n x m + 1
#' @author Nikolai Sellereite
weight_matrix_cpp <- function(features, m, n, w) {
    .Call(`_shapr_weight_matrix_cpp`, features, m, n, w)
}

#' Get feature matrix
#'
#' @param features List
#' @param nfeatures Positive integer. Total number of features
#'
#' @export
#'
#' @return Matrix
#' @author Nikolai Sellereite
feature_matrix_cpp <- function(features, nfeatures) {
    .Call(`_shapr_feature_matrix_cpp`, features, nfeatures)
}

