# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get distance
#'
#' @param features List
#' @param Xtrain Dataframe
#' @param Xtest Dataframe
#' @param ncomb Positive integer
#' @param sigma Positive numeric
#'
#' @export
#'
#' @return Array of three dimensions
#' @author Nikolai Sellereite
distance_cpp <- function(features, Xtrain, Xtest, ncomb, sigma) {
    .Call(`_shapr_distance_cpp`, features, Xtrain, Xtest, ncomb, sigma)
}

#' Get imputed data
#'
#' @param features List
#' @param Xtrain Dataframe
#' @param Xtest Dataframe
#' @param ncomb Positive integer
#' @param sigma Positive numeric
#'
#' @export
#'
#' @return Array of three dimensions
#' @author Nikolai Sellereite
impute_cpp <- function(I, Xtrain, Xtest, features) {
    .Call(`_shapr_impute_cpp`, I, Xtrain, Xtest, features)
}

#' Get distance
#'
#' @param D Three dimnesional array
#'
#' @export
#'
#' @return List
#' @author Nikolai Sellereite
sample_cpp <- function(D, nsamples, ncomb) {
    .Call(`_shapr_sample_cpp`, D, nsamples, ncomb)
}

#' Get distance
#'
#' @param comb List
#' @param v Postive numberic vector
#' @param m Postive integer. Number of features
#' @param n Postive integer. Number of combinations
#'
#' @export
#'
#' @return Matrix of dimension n x m + 1
#' @author Nikolai Sellereite
weighted_matrix <- function(comb, w, m, n) {
    .Call(`_shapr_weighted_matrix`, comb, w, m, n)
}

