# 01.09.23: Moved from ubuntu-latest to ubuntu-20.04 to avoid actions being cancelled
# This is potentially due to CPU quota being exceeded as suggested
# here: https://github.com/actions/runner-images/issues/6680 and
# here: https://github.com/actions/runner-images/discussions/7188)

# July 5th, 2022: This is a modifided version of the 'check-standard' version from
# https://github.com/r-lib/actions/tree/v2/examples#standard-ci-workflow

# The following is modified:

# 1. Runs on branches cranversion and devel as well
# 2. Runs on oldrel-2 as well
# 3. R CMD check is performed WITHOUT the default as-cran flag. This allows snapshots to run without setting
#    as-cran=TRUE in every single call to expect_snapshot


# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
  push:
    branches: [main, master, cranversion, devel]
  pull_request:
    branches: [main, master, cranversion, devel]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-20.04,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-20.04,   r: 'release'}
          - {os: ubuntu-20.04,   r: 'oldrel-1'}
          - {os: ubuntu-20.04,   r: 'oldrel-2'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual")' # I.e. exclude the as-cran comment here
          upload-snapshots: true
