# 01.09.23: Moved from ubuntu-latest to ubuntu-20.04 to avoid actions being cancelled
# This is potentially due to CPU quota being exceeded as suggested
# here: https://github.com/actions/runner-images/issues/6680 and
# here: https://github.com/actions/runner-images/discussions/7188)


name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 week'
        skip-recent: 6
        # Optional inputs
        # skip-tags: true
